services:
  social_postgres:
    container_name: 'social_postgres'
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=social'
      - 'POSTGRES_PASSWORD=Social!23'
      - 'POSTGRES_USER=social'
    ports:
      - '5432:5432'
  social_pgadmin4:
    container_name: "social_pgadmin4"
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - social_postgres